words = [
['que', 'that'],
['de', 'of'],
['no', 'No'],
['a', 'to'],
['la', 'the'],
['el', 'he'],
['es', 'is'],
['y', 'and'],
['en', 'in'],
['lo', 'it'],
['un', 'a'],
['por', 'by'],
['qué', 'that'],
['me', 'I'],
['una', 'a'],
['te', 'tea'],
['los', 'the'],
['se', 'HE'],
['con', 'with'],
['para', 'for'],
['mi', 'my'],
['está', 'this'],
['si', 'Yeah'],
['bien', 'good'],
['pero', 'but'],
['yo', 'I'],
['eso', 'that'],
['las', 'the'],
['sí', 'Yeah'],
['su', 'his'],
['tu', 'you'],
['aquí', 'here'],
['del', 'of the'],
['al', 'to the'],
['como', 'as'],
['le', 'you'],
['más', 'further'],
['esto', 'this'],
['ya', 'already'],
['todo', 'all'],
['esta', 'this'],
['vamos', 'come on'],
['muy', 'very'],
['hay', 'there is'],
['ahora', 'now'],
['algo', 'something'],
['estoy', 'I\'m'],
['tengo', 'I have'],
['nos', 'us'],
['tú', 'you'],
]
