// Generated by generate.py from questions.md. Do not edit by hand.
const CATEGORIES = [
	{
		"name": "Financial Transparency",
		"clues": [
			{
				"clue": "Audit, annual budget",
				"question": "What are two items that must be posted on the website?",
				"value": 100
			},
			{
				"clue": "Board Treasurer",
				"question": "Who is responsible that the board is complying with financial transparency law?",
				"value": 200
			},
			{
				"clue": "Within 60 days and for two years",
				"question": "How quickly do financial records need to be posted and how long do they need to stay on the website?",
				"value": 300
			},
			{
				"clue": "Downloadable for free",
				"question": "What Financial documents on the website must be?",
				"value": 400
			},
			{
				"clue": "Form 990",
				"question": "The iRS tax filing for non-profits?",
				"value": 500
			}
		]
	},
	{
		"name": "Open Meeting Law",
		"clues": [
			{
				"clue": "Any meeting of more than 2 Board members",
				"question": "What must be noticed and open to the public?",
				"value": 100
			},
			{
				"clue": "Discussing decisions prior to a Board meeting through a series of emails or phone calls between Board members",
				"question": "What is called a chain meeting?",
				"value": 200
			},
			{
				"clue": "Agendas and Minutes",
				"question": "What must be posted on the website about board meetings?",
				"value": 300
			},
			{
				"clue": "All Board votes",
				"question": "What must always be in open session?",
				"value": 400
			},
			{
				"clue": "A meeting of the Board that is not open to the public",
				"question": "What is called an Executive Session?",
				"value": 500
			}
		]
	},
	{
		"name": "ADA and IDEA",
		"clues": [
			{
				"clue": "Adjustments made to curriculum and instruction to support a student with disabilities or to a work assignment to support an employee with an injury",
				"question": "What is an accommodation?",
				"value": 100
			},
			{
				"clue": "The right to a Free Appropriate Public Education",
				"question": "What is FAPE?",
				"value": 200
			},
			{
				"clue": "Students with learning disabilities that require individualized education plans",
				"question": "Who is in the special education program?",
				"value": 300
			},
			{
				"clue": "The number of types of disabilities that schools can turn students away for",
				"question": "What is 0?",
				"value": 400
			},
			{
				"clue": "School staff, special education teacher, parents, a school administrator",
				"question": "Who is on the team to decide what a students needs in special education?",
				"value": 500
			}
		]
	},
	{
		"name": "Title IX or  CO Discrimination?",
		"clues": [
			{
				"clue": "A complaint of repeated sexual harassment that is causing a student to be afraid to go to school",
				"question": "What is a Title IX complaint?",
				"value": 100
			},
			{
				"clue": "A complaint about being forbidden from wearing a hijab at school",
				"question": "What is a Colorado discrimination complaint?",
				"value": 200
			},
			{
				"clue": "A complaint about being bullied for being gay",
				"question": "What is a Colorado discrimination complaint?",
				"value": 300
			},
			{
				"clue": "A complaint about students using a racial slur on the playground",
				"question": "What is a Colorado discrimination complaint?",
				"value": 400
			},
			{
				"clue": "A complaint about a student making sexually explicit jokes at lunch",
				"question": "What is a Colorado discrimination complaint and maybe a title IX complaint?",
				"value": 500
			}
		]
	},
	{
		"name": "Top Reasons Charter Schools Close",
		"clues": [
			{
				"clue": "Under enrollment of students",
				"question": "Why the budget revenue would be much lower than planned?",
				"value": 100
			},
			{
				"clue": "Using school funds for personal expenses",
				"question": "What is mismanagement of funds or embezzlement?",
				"value": 200
			},
			{
				"clue": "Receiving a red or turn around rating on the school performance framework (SPF)",
				"question": "What is a poor or failing academic program?",
				"value": 300
			},
			{
				"clue": "Soaring facilities costs forces cuts to the program that make it no longer appealing to families",
				"question": "Poor financial planning?",
				"value": 400
			},
			{
				"clue": "The entire Board steps down and no one will volunteer to take over",
				"question": "What is a governance breakdown?",
				"value": 500
			}
		]
	}
];
