#!/usr/bin/env python3
"""Parses questions.md and (re)generates data.js and the <table> in index.html.

Run with: python3 generate.py
"""

import json
import os
import re

DIR = os.path.dirname(os.path.abspath(__file__))
VALUES = [100, 200, 300, 400, 500]


def escape_html(text):
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def parse_questions(raw):
    categories = []
    current = None
    pending_clue = None

    for line in raw.split("\n"):
        if re.match(r"^\d+\.\s", line):
            current = {"name": re.sub(r"^\d+\.\s*", "", line).strip(), "clues": []}
            categories.append(current)
        elif re.match(r"^        \S", line):
            if current is not None and pending_clue is not None:
                question = line.strip()
                if not question.endswith("?"):
                    question += "?"
                pending_clue["question"] = question
                current["clues"].append(pending_clue)
                pending_clue = None
        elif re.match(r"^    \S", line):
            pending_clue = {"clue": line.strip()}

    for cat in categories:
        if len(cat["clues"]) != len(VALUES):
            raise ValueError(
                f'Category "{cat["name"]}" has {len(cat["clues"])} clues, expected {len(VALUES)}'
            )
        for i, clue in enumerate(cat["clues"]):
            clue["value"] = VALUES[i]

    return categories


def write_data_js(categories):
    content = (
        "// Generated by generate.py from questions.md. Do not edit by hand.\n"
        "const CATEGORIES = "
        + json.dumps(categories, indent="\t")
        + ";\n"
    )
    with open(os.path.join(DIR, "data.js"), "w") as f:
        f.write(content)


def build_table(categories):
    header_cells = "\n".join(
        f'\t\t\t\t\t<th onclick="this.style.opacity = 1">{escape_html(c["name"])}</th>'
        for c in categories
    )

    body_rows = []
    for vi, v in enumerate(VALUES):
        cells = "\n".join(
            f'\t\t\t\t\t<td class="unknown" onclick="showClue({ci}, {vi}, this)">{v}</td>'
            for ci, c in enumerate(categories)
        )
        body_rows.append(f"\t\t\t\t<tr>\n{cells}\n\t\t\t\t</tr>")

    return (
        "\t\t\t<table>\n"
        "\t\t\t\t<tr>\n"
        + header_cells
        + "\n\t\t\t\t</tr>\n"
        + "\n".join(body_rows)
        + "\n\t\t\t</table>"
    )


def write_index_html(categories):
    table = build_table(categories)

    html = f"""<!DOCTYPE html>
<html>
\t<head>
\t\t<title>Board Jeopardy!</title>
\t\t<link rel="stylesheet" href="style.css"/>
\t\t<script src="data.js"></script>
\t\t<script src="script.js"></script>
\t</head>
\t<body>
\t\t<h1>Board Jeopardy!</h1>
\t\t<div id="DadScore" contenteditable="true" onblur="updateDad()">TEAM A: 0</div>
\t\t<div id="FamilyScore" contenteditable="true" onblur="updateFam()">TEAM B: 0</div>
{table}
\t\t<div id="popup">
\t\t\t<div id="floater">
\t\t\t\t<h1 id="titleCard">Category for Value</h1>
\t\t\t\t<div id="exit" onclick="document.getElementById('popup').style.display = 'none';">&times;</div>
\t\t\t\t<div id="clue">Clue</div>
\t\t\t\t<div id="question">
\t\t\t\t\t<span id="questionPrompt" onclick="revealQuestion()">Click to Reveal</span>
\t\t\t\t\t<span id="questionAnswer" onclick="revealQuestion()"></span>
\t\t\t\t</div>
\t\t\t\t<h2 id="scoreButtons">
\t\t\t\t\t<span onclick="dadPoints()">TEAM A</span> | <span onclick="famPoints()">TEAM B</span>
\t\t\t\t</h2>
\t\t\t</div>
\t\t</div>
\t</body>
</html>
"""

    with open(os.path.join(DIR, "index.html"), "w") as f:
        f.write(html)


def main():
    with open(os.path.join(DIR, "questions.md")) as f:
        raw = f.read()
    categories = parse_questions(raw)
    write_data_js(categories)
    write_index_html(categories)
    print(f"Generated data.js and index.html from {len(categories)} categories.")


if __name__ == "__main__":
    main()
